{{- if and .Values.rbac.create (eq (include "neo4j-operator.createClusterRole" .) "true") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "neo4j-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "neo4j-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "neo4j-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "neo4j-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
