{{- if and .Values.rbac.create (eq .Values.operatorMode "namespace") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "neo4j-operator.fullname" . }}-manager-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neo4j-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "neo4j-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "neo4j-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
