apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: neo4j-operator
  name: neo4j-operator-neo4jenterprisecluster-viewer-role
rules:
- apiGroups:
  - neo4j.neo4j.com
  resources:
  - neo4jenterpriseclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - neo4j.neo4j.com
  resources:
  - neo4jenterpriseclusters/status
  verbs:
  - get
