apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests.yaml
- webhook-service.yaml

patches:
- target:
    kind: ValidatingWebhookConfiguration
  patch: |-
    - op: replace
      path: /webhooks/0/clientConfig/service/namespace
      value: neo4j-operator-system
- target:
    kind: MutatingWebhookConfiguration
  patch: |-
    - op: replace
      path: /webhooks/0/clientConfig/service/namespace
      value: neo4j-operator-system
