# permissions for end users to view neo4jdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: neo4j-operator
    app.kubernetes.io/managed-by: kustomize
  name: neo4jdatabase-viewer-role
rules:
- apiGroups:
  - neo4j.neo4j.com
  resources:
  - neo4jdatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - neo4j.neo4j.com
  resources:
  - neo4jdatabases/status
  verbs:
  - get
