# permissions for end users to edit neo4jbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: neo4j-operator
    app.kubernetes.io/managed-by: kustomize
  name: neo4jbackup-editor-role
rules:
- apiGroups:
  - neo4j.neo4j.com
  resources:
  - neo4jbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neo4j.neo4j.com
  resources:
  - neo4jbackups/status
  verbs:
  - get
