apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - neo4j_v1alpha1_neo4jplugin_cluster.yaml
  - neo4j_v1alpha1_neo4jplugin_standalone.yaml
  - neo4j_v1alpha1_neo4jenterprisecluster.yaml
  - neo4j_v1alpha1_neo4jenterprisestandalone.yaml
  - neo4j_v1alpha1_neo4jdatabase.yaml
  - neo4j_v1alpha1_neo4jbackup.yaml
  - neo4j_v1alpha1_neo4jrestore.yaml
  - neo4j_v1alpha1_neo4jshardeddatabase.yaml
