apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jRestore
metadata:
  name: example-restore
spec:
  targetCluster: sample-cluster
  databaseName: exampledb
  source:
    type: backup
    backupRef: example-backup
