apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: sample-cluster
spec:
  image:
    repo: neo4j
    tag: 5.26.0-enterprise
  topology:
    servers: 3
  storage:
    className: standard
    size: 10Gi
  auth:
    adminSecret: neo4j-admin-secret
