apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jShardedDatabase
metadata:
  name: example-sharded
spec:
  clusterRef: sample-cluster
  name: shardeddb
  defaultCypherLanguage: "25"
  propertySharding:
    propertyShards: 2
    graphShard:
      primaries: 1
      secondaries: 0
    propertyShardTopology:
      replicas: 1
