apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: neo4j-operator-controller-manager
    app.kubernetes.io/name: neo4j-operator
    app.kubernetes.io/managed-by: kustomize
  name: neo4j-operator-controller-manager-metrics-service
  namespace: neo4j-operator-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: neo4j-operator-controller-manager
